language: node_js
node_js:
  - "7.10"
  - "7.9"
  - "7.8"
  - "7.7"
  - "7.6"
  - "7.5"
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "6"
  - "4"
before_script:
  - git clone --depth 1 https://github.com/APIs-guru/openapi-directory.git
  - git clone --depth 1 https://github.com/mermade/openapi-definitions.git
  - git clone --depth 1 https://github.com/SOM-Research/hapi.git
  - git clone --depth 1 https://github.com/mermade/openapi3-examples.git
script:
  - travis_wait node testRunner -q openapi-directory/APIs/
  - travis_wait node testRunner -q openapi-definitions/
  - travis_wait node testRunner -q hapi/APIs/
  - travis_wait node testRunner -q openapi3-examples/pass
  - travis_wait node testRunner -q -f openapi3-examples/fail

